# Render deployment configuration
services:
  - type: web
    name: connectcore-api
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    numInstances: 1
    disk:
      name: connectcore-disk
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: PORT
        value: 8080
      - key: ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT
        value: Information
      - key: ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT
        value: Warning
